# This file contains the CI/CD Pipeline in GitLab

variables:
  TAG: $CI_COMMIT_REF_NAME
  PROXY: "http://$WB_HTTP_PROXY_HOST:$WB_HTTP_PROXY_PORT"

stages:
  - build
  - scan
  - test

cache:
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull-push
  paths:
    - target/

build:docker:
  stage: build
  only:
    refs:
      - master
      - tags
  tags:
    - run_shell
  script:
    - "docker build
      --build-arg HTTP_PROXY=$PROXY
      --build-arg HTTPS_PROXY=$PROXY
      --tag $MTR_URL/depoy:$TAG
      --file Dockerfile ."

    - docker push $MTR_URL/depoy:$TAG
    - docker image rm $MTR_URL/depoy:$TAG

  artifacts:
    paths:
      - target/depoy

    expire_in: 1 hour

sonar scan:
  stage: scan
  image: $MTR_URL/sonar-scanner:master
  only:
    refs:
      - master
      - tags

  variables:
    SONAR_OPTS: " -Dsonar.sources=./depoy/
      -Dsonar.projectKey=depoy
      -Dsonar.host.url=$SONAR_HOST_URL
      -Dsonar.login=58f3327099aa01d9eaaf8fe7a7bbe8a9cbda2b00
      -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA
      -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME
      -Dsonar.gitlab.project_id=$CI_PROJECT_ID
      -Dsonar.branch.name=$CI_COMMIT_REF_NAME
      -Dsonar.go.tests.reportPaths=target/test-report.out
      -Dsonar.go.coverage.reportPaths=target/coverage-report.out
      -Dsonar.tests=./depoy/
      -Dsonar.test.inclusions=./src/**/*_test.go
      -Dsonar.test.exclusions=./src/**/vendor/**
      --debug -Dsonar.verbose=true"
  tags:
    - run_docker
  script:
    - "sonar-scanner $SONAR_OPTS"
