# This file contains the CI/CD Pipeline in GitLab

variables:
  TAG: $CI_COMMIT_REF_NAME
  PROXY: "http://$WB_HTTP_PROXY_HOST:$WB_HTTP_PROXY_PORT"
  GO_VERSION: "1.15"

stages:
  - build1
  - build2
  - build3

cache:
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull-push
  paths:
    - webapp/dist

build:vue:
  stage: build1
  tags:
    - run_docker
  image: node
  script:
    - cd webapp
    - npm install 
    - npm run build
  artifacts:
    paths:
      - webapp/dist
    expire_in: 1 hour

build:go:
  stage: build2
  tags:
    - run_docker
  image: golang:$GO_VERSION
  script:
    - ls -ltr webapp/dist
    - go env -w GOOS=linux GOARCH=amd64 CGO_ENABLED=0 
    - go get -u github.com/gobuffalo/packr/packr
    - packr build -a -o depoy .
    - ls -ltr
  artifacts:
    paths:
      - depoy
    expire_in: 1 hour

build:docker:
  stage: build3
  tags:
    - run_shell
  script:
    - "docker build
      --build-arg HTTP_PROXY=$PROXY
      --build-arg HTTPS_PROXY=$PROXY
      --tag $MTR_URL/depoy:$TAG
      --file Dockerfile ."

    - docker push $MTR_URL/depoy:$TAG
    - docker image rm $MTR_URL/depoy:$TAG
