matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      before_script:
        - cd webapp
      script:
        - npm install
        - npm run build

    - language: go
      go:
        - "1.15"
      before_script:
        - go get -t -v ./...
      scrpt:
        - export GO111MODULE=on
        - go test -v ./...
        - go build github.com/rgumi/depoy
