matrix:
  include:
    - language: node_js
      node:
        - "node"
      before_script:
        - cd vue
      script:
        - npm install
        - npm run build

    - language: go
      go:
        - "1.15"
      before_script:
        - cd src
      scrpt:
        - go env -w GO111MODULE=on -w GOOS=linux -w GOARCH=amd64
        - go test ./... -coverprofile="coverage-report.out"
        - go test ./... -json > test-report.out
        - go build

notifications:
  email:
    - ron.gummich@outlook.de
