matrix:
  include:
    - language: node_js
      node_js:
        - "node"
      before_script:
        - cd vue
      script:
        - npm install
        - npm run build

    - language: go
      go:
        - "1.15"
      before_script:
        - cd src
        - go vet ./...
      scrpt:
        - export GO111MODULE=on
        - export GOOS=linux
        - export GOARCH=amd64
        - export GOPATH=$PWD:$GOPATH

        - go get -t -v ./...
        - go test -v ./...
        - go build
