FROM node:lts-alpine as vueBuilder
WORKDIR /app
COPY webapp ./
RUN npm install
RUN npm run build

FROM golang:latest as appBuilder
WORKDIR /go/src/github.com/rgumi/depoy/
COPY . .
COPY --from=vueBuilder /app/dist .
RUN go get -u github.com/gobuffalo/packr/v2/packr2
RUN GOOS=linux GOARCH=amd64 CGO_ENABLED=0 packr2 build -a -o depoy .

FROM alpine:latest
RUN set -x && \
    addgroup -S depoy && adduser -S -G depoy depoy && \
    mkdir -p  /home/depoy/data && \
    chown -R depoy:depoy /home/depoy
USER depoy
WORKDIR /home/depoy
COPY --from=appBuilder /go/src/github.com/rgumi/depoy/depoy .
VOLUME /home/depoy/data

EXPOSE 8080/tcp
EXPOSE 8443/tcp
EXPOSE 8081/tcp
EXPOSE 8444/tcp
ENTRYPOINT ["./depoy"]