FROM node:lts-alpine as vueBuilder
WORKDIR /app
COPY webapp/package*.json ./
RUN npm install
COPY webapp/* ./
RUN ls -l && npm run build

FROM golang:latest as appBuilder
WORKDIR /go/src/github.com/rgumi/depoy/
COPY . .
COPY --from=vueBuilder /app/dist .
RUN ls -l && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build

FROM alpine:latest
RUN set -x && \
    addgroup -S depoy && adduser -S -G depoy depoy && \
    mkdir -p  /home/depoy/data && \
    chown -R depoy:depoy /home/depoy
USER depoy
WORKDIR /home/depoy
COPY --from=appBuilder /go/src/github.com/rgumi/depoy/depoy .
VOLUME /home/depoy/data

EXPOSE 8080/tcp
EXPOSE 8443/tcp
EXPOSE 8081/tcp
EXPOSE 8444/tcp

ENTRYPOINT ["./depoy"]