apiVersion: v1
kind: ConfigMap
metadata:
  name: depoy-server-conf
  labels:
    name: depoy-server-conf
  namespace: ingress-depoy
data:
  gateway-config.yaml: |-
    addr: :8080
    read_timeout: 10s
    write_timeout: 10s
    scrape_interval: 5s
    routes:
      - name: Grafana
        prefix: /grafana/
        host: "*"
        rewrite: /grafana/
        cookieTTL: 2m0s
        strategy:
          type: sticky
        healthcheck_bool: true
        timeout: 5s
        idleTimeout: 30s
        proxy: ""
        backends:
          - name: grafana
            addr: http://grafana-web.monitoring:3000
            weight: 100
            metricThresholds:          
              - metric: ResponseTime
                operator: ">"
                threshold: 1000
                active_for: 10s
              - metric: 6xxRate
                operator: ">"
                threshold: 0.1
                active_for: 10s
      - name: Prometheus
        prefix: /prom/
        host: "*"
        rewrite: /prom/
        cookieTTL: 2m0s
        strategy:
          type: sticky
        healthcheck_bool: true
        timeout: 5s
        idleTimeout: 30s
        proxy: ""
        backends:
          - name: prometheus
            addr: http://prometheus-web.monitoring:8080
            weight: 100
            metricThresholds:          
              - metric: ResponseTime
                operator: ">"
                threshold: 1000
                active_for: 10s
              - metric: 6xxRate
                operator: ">"
                threshold: 0.1
                active_for: 10s
      - name: Kubernetes Dashboard
        prefix: /
        host: "*"
        rewrite: /
        cookieTTL: 2m0s
        strategy:
          type: sticky
        healthcheck_bool: true
        timeout: 5s
        idleTimeout: 30s
        proxy: ""
        backends:
          - name: k8s-dashboard
            addr: https://kubernetes-dashboard.kubernetes-dashboard:443
            weight: 100
            metricThresholds:          
              - metric: ResponseTime
                operator: ">"
                threshold: 1000
                active_for: 10s
              - metric: 6xxRate
                operator: ">"
                threshold: 0.1
                active_for: 10s
      - name: WAHub Dummy
        prefix: /wahub/
        host: "*"
        rewrite: /watest/
        cookieTTL: 10m
        strategy:
          type: sticky
        healthcheck_bool: true
        timeout: 10s
        idleTimeout: 30s
        proxy: ""
        backends:
          - name: v0-1-0
            addr: "http://v0-1-0-wabizdummy-svc.depoy-testing:8080"
            weight: 100
            healthcheckUrl: "http://v0-1-0-wabizdummy-svc.depoy-testing:8081/prometheus"
            metricThresholds:          
              - metric: ResponseTime
                operator: ">"
                threshold: 1000
                active_for: 10s
                resolve_in: 5s
              - metric: 5xxRate
                operator: ">"
                threshold: 0.3
                active_for: 5s
                resolve_in: 20s
