apiVersion: v1
kind: ConfigMap
metadata:
  name: depoy-server-conf
  labels:
    name: depoy-server-conf
  namespace: ingress-depoy
data:
  gateway-config.yaml: |-
    addr: :8080
    read_timeout: 10s
    write_timeout: 10s
    scrape_interval: 5s
    routes:
      - name: Grafana
        prefix: /grafana/
        methods:
          - GET
          - POST
        host: "*"
        rewrite: /grafana/
        cookieTTL: 2m0s
        strategy:
          type: sticky
        healthcheck: true
        timeout: 5s
        idleTimeout: 5s
        proxy: ""
        backends:
          - name: grafana
            addr: http://grafana-web.monitoring:3000
            weight: 100
            metric_thresholds:          
              - metric: ResponseTime
                operator: ">"
                threshold: 1000
                active_for: 10s
              - metric: 6xxRate
                operator: ">"
                threshold: 0.1
                active_for: 10s
      - name: Prometheus
        prefix: /prom/
        methods:
          - GET
          - POST
        host: "*"
        rewrite: /prom/
        cookieTTL: 2m0s
        strategy:
          type: sticky
        healthcheck: true
        timeout: 5s
        idleTimeout: 5s
        proxy: ""
        backends:
          - name: prometheus
            addr: http://prometheus-web.monitoring:8080
            weight: 100
            metric_thresholds:          
              - metric: ResponseTime
                operator: ">"
                threshold: 1000
                active_for: 10s
              - metric: 6xxRate
                operator: ">"
                threshold: 0.1
                active_for: 10s
      - name: Kubernetes Dashboard
        prefix: /
        methods:
          - GET
          - POST
        host: "*"
        rewrite: /
        cookieTTL: 2m0s
        strategy:
          type: sticky
        healthcheck: true
        timeout: 5s
        idleTimeout: 5s
        proxy: ""
        backends:
          - name: k8s-dashboard
            addr: https://kubernetes-dashboard.kubernetes-dashboard:443
            weight: 100
            metric_thresholds:          
              - metric: ResponseTime
                operator: ">"
                threshold: 1000
                active_for: 10s
              - metric: 6xxRate
                operator: ">"
                threshold: 0.1
                active_for: 10s
      - name: Whatsapp Dummy
        prefix: /watest/
        methods:
          - GET
          - POST
        host: "*"
        rewrite: /watest/
        cookieTTL: 2m0s
        strategy:
          type: sticky
        healthcheck: true
        timeout: 5s
        idleTimeout: 5s
        proxy: ""
        backends:
          - name: dashboard
            addr: http://wabizdummy-svc.whatsapp:8080
            weight: 100
            metric_thresholds:          
              - metric: ResponseTime
                operator: ">"
                threshold: 1000
                active_for: 10s
              - metric: 6xxRate
                operator: ">"
                threshold: 0.1
                active_for: 10s
