apiVersion: v1
kind: ConfigMap
metadata:
  name: depoy-server-conf
  labels:
    name: depoy-server-conf
  namespace: ingress-depoy
data:
  gateway-config.yaml: |-
    addr: :8080
    read_timeout: 10s
    write_timeout: 10s
    scrape_interval: 5s
    routes:
      Grafana:
        name: Grafana
        prefix: /grafana/
        methods:
          - GET
          - POST
        host: "*"
        rewrite: /grafana/
        cookieTTL: 2m0s
        strategy:
          type: sticky
        healthcheck: true
        timeout: 5s
        idleTimeout: 5s
        proxy: ""
        backends:
          e9cfa68e-78ab-4d90-8648-8cdc5bec0f48:
            id: e9cfa68e-78ab-4d90-8648-8cdc5bec0f48
            name: grafana1
            addr: http://grafana-web.monitoring:3000
            weight: 100
            metric_thresholds:          
              - metric: ResponseTime
                operator: ">"
                threshold: 1000
                active_for: 10s
              - metric: 6xxRate
                operator: ">"
                threshold: 0.1
                active_for: 10s
