addr: :8080
readTimeout: 5s
writeTimeout: 5s
idleTimeout: 10s
httpTimeout: 10s
routes:
  - name: Route1
    prefix: /route1/
    host: "*"
    rewrite: /
    cookieTTL: 10m
    strategy:
      type: sticky
    healthcheckBool: true
    writeTimeout: 20s
    readTimeout: 15s
    idleTimeout: 10s
    proxy: ""
    backends:
      - name: b1
        addr: "http://localhost:7070"
        weight: 100
        healthcheckUrl: "http://localhost:7070/"
        scrapeUrl: "http://localhost:7071/metrics"
        scrapeMetrics: ["go_goroutines"]
        metricThresholds:
          - metric: ResponseTime
            operator: ">"
            threshold: 1000
            activeFor: 10s
            resolveIn: 5s
          - metric: 5xxRate
            operator: ">"
            threshold: 0.3
            activeFor: 5s
            resolveIn: 0s
      - name: b2
        addr: "http://localhost:9090"
        weight: 0
        healthcheckUrl: "http://localhost:9090/"
        scrapeUrl: "http://localhost:9091/metrics"
        scrapeMetrics: ["go_goroutines"]
        metricThresholds:
          - metric: ResponseTime
            operator: ">"
            threshold: 1000
            activeFor: 10s
            resolveIn: 5s
          - metric: 5xxRate
            operator: ">"
            threshold: 0.3
            activeFor: 5s
            resolveIn: 0s