addr: :8080
read_timeout: 10s
write_timeout: 10s
scrape_interval: 5s
routes:
    - name: RouteHeader
      prefix: /header/
      methods:
        - GET
        - POST
      host: '*'
      rewrite: /
      cookieTTL: 2m0s
      strategy:
        type: header
        header_name: ToTest2
        header_value: "true"
        old_backend: Test1
        new_backend: Test2
      healthcheck: true
      timeout: 5s
      idleTimeout: 5s
      proxy: ""
      backends:
        - id: b90733ec-43c5-40d3-80b0-f5220f8995db
          name: Test2
          addr: http://localhost:9090
          weight: 100
          active: true
          scrape_url: http://localhost:9091/metrics
          scrape_metrics:
            - go_goroutines
          metric_thresholds:
            - metric: ResponseTime
              operator: '>'
              threshold: 1000
              active_for: 10ns
            - metric: 6xxRate
              operator: '>'
              threshold: 0.1
              active_for: 10ns
          healthcheck_url: http://localhost:9090/
        - id: 2726a619-6c2e-40bc-9222-2269c3d25f03
          name: Test1
          addr: http://localhost:7070
          weight: 100
          active: true
          scrape_url: http://localhost:7071/metrics
          scrape_metrics:
            - go_goroutines
          metric_thresholds:
            - metric: ResponseTime
              operator: '>'
              threshold: 1000
              active_for: 10ns
            - metric: 6xxRate
              operator: '>'
              threshold: 0.1
              active_for: 10ns
            - metric: 5xxRate
              operator: '>'
              threshold: 0.3
              active_for: 10ns
            - metric: 4xxRate
              operator: '>'
              threshold: 0.6
              active_for: 10ns
          healthcheck_url: http://localhost:7070/
    - name: RouteSlippery
      prefix: /slippery/
      methods:
        - GET
        - POST
      host: '*'
      rewrite: /
      cookieTTL: 2m0s
      strategy:
        type: slippery
      healthcheck: true
      timeout: 5s
      idleTimeout: 5s
      proxy: ""
      backends:
        - id: 1aa5a24d-d0dd-4605-8bb6-8c60c07de49f
          name: Test1
          addr: http://localhost:7070
          weight: 100
          active: true
          scrape_url: http://localhost:7071/metrics
          scrape_metrics:
            - go_goroutines
          metric_thresholds:
            - metric: ResponseTime
              operator: '>'
              threshold: 1000
              active_for: 10ns
            - metric: 6xxRate
              operator: '>'
              threshold: 0.1
              active_for: 10ns
            - metric: 5xxRate
              operator: '>'
              threshold: 0.3
              active_for: 10ns
            - metric: 4xxRate
              operator: '>'
              threshold: 0.6
              active_for: 10ns
          healthcheck_url: http://localhost:7070/
        - id: a3b93778-69ef-4754-8671-358050af93e7
          name: Test2
          addr: http://localhost:9090
          weight: 100
          active: true
          scrape_url: http://localhost:9091/metrics
          scrape_metrics:
            - go_goroutines
          metric_thresholds:
            - metric: ResponseTime
              operator: '>'
              threshold: 1000
              active_for: 10ns
            - metric: 6xxRate
              operator: '>'
              threshold: 0.1
              active_for: 10ns
          healthcheck_url: http://localhost:9090/
    - name: RouteSticky
      prefix: /sticky/
      methods:
        - GET
        - POST
      host: '*'
      rewrite: /
      cookieTTL: 2m0s
      strategy:
        type: sticky
      healthcheck: true
      timeout: 5s
      idleTimeout: 5s
      proxy: ""
      backends:
        - id: 6bdaf5d1-3675-4790-a6b4-812f1deb3483
          name: Test1
          addr: http://localhost:7070
          weight: 100
          active: true
          scrape_url: http://localhost:7071/metrics
          scrape_metrics:
            - go_goroutines
          metric_thresholds:
            - metric: ResponseTime
              operator: '>'
              threshold: 1000
              active_for: 10ns
            - metric: 6xxRate
              operator: '>'
              threshold: 0.1
              active_for: 10ns
            - metric: 5xxRate
              operator: '>'
              threshold: 0.3
              active_for: 10ns
            - metric: 4xxRate
              operator: '>'
              threshold: 0.6
              active_for: 10ns
          healthcheck_url: http://localhost:7070/
        - id: 88303d60-1812-4bdb-89a9-2672946916eb
          name: Test2
          addr: http://localhost:9090
          weight: 100
          active: true
          scrape_url: http://localhost:9091/metrics
          scrape_metrics:
            - go_goroutines
          metric_thresholds:
            - metric: ResponseTime
              operator: '>'
              threshold: 1000
              active_for: 10ns
            - metric: 6xxRate
              operator: '>'
              threshold: 0.1
              active_for: 10ns
          healthcheck_url: http://localhost:9090/
    - name: RouteShadow
      prefix: /shadow/
      methods:
        - GET
        - POST
      host: '*'
      rewrite: /
      cookieTTL: 2m0s
      strategy:
        type: shadow
        shadow_backend: Test2
      healthcheck: true
      timeout: 5s
      idleTimeout: 5s
      proxy: ""
      backends:
        - id: e5af2490-b21f-4914-9627-aceb4a2df228
          name: Test1
          addr: http://localhost:7070
          weight: 100
          active: true
          scrape_url: http://localhost:7071/metrics
          scrape_metrics:
            - go_goroutines
          metric_thresholds:
            - metric: ResponseTime
              operator: '>'
              threshold: 1000
              active_for: 10ns
            - metric: 6xxRate
              operator: '>'
              threshold: 0.1
              active_for: 10ns
            - metric: 5xxRate
              operator: '>'
              threshold: 0.3
              active_for: 10ns
            - metric: 4xxRate
              operator: '>'
              threshold: 0.6
              active_for: 10ns
          healthcheck_url: http://localhost:7070/
        - id: c33ebc59-ce6f-45bb-b7f2-ea554db60b1e
          name: Test2
          addr: http://localhost:9090
          weight: 0
          active: true
          scrape_url: http://localhost:9091/metrics
          scrape_metrics:
            - go_goroutines
          metric_thresholds:
            - metric: ResponseTime
              operator: '>'
              threshold: 1000
              active_for: 10ns
            - metric: 6xxRate
              operator: '>'
              threshold: 0.1
              active_for: 10ns
          healthcheck_url: http://localhost:9090/
