routes:
  - name: Route1
    prefix: /route1/
    rewrite: /
    strategy:
      type: sticky
    backends:
      - name: backend1
        addr: http://localhost:7070
        weight: 100
        metricThresholds:
          - metric: ResponseTime
            operator: ">"
            threshold: 1000
            resolveIn: 5s
          - metric: "5xxRate"
            operator: ">"
            threshold: 0.2
            activeFor: 2s
            resolveIn: 0s
          - metric: "4xxRate"
            operator: ">"
            threshold: 0.3
            resolveIn: 5000
      - name: backend2
        addr: http://localhost:9090
        weight: 100
        metricThresholds:
          - metric: ResponseTime
            operator: ">"
            threshold: 1000
            resolveIn: 5000
          - metric: "5xxRate"
            operator: ">"
            threshold: 0.2
            activeFor: 2s
            resolveIn: 0s
          - metric: "4xxRate"
            operator: ">"
            threshold: 0.3
            resolveIn: 5000
      - name: b3
        addr: http://localhost:9090
        weight: 100
        metricThresholds:
          - metric: ResponseTime
            operator: ">"
            threshold: 1000
          - metric: "5xxRate"
            operator: ">"
            threshold: 0.2
            activeFor: 2s
            resolveIn: 0s
  - name: Route2
    prefix: /route2/
    rewrite: /
    strategy:
      type: sticky
    backends:
      - name: b1
        addr: http://localhost:7070
        weight: 100
        metricThresholds:
          - metric: ResponseTime
            operator: ">"
            threshold: 1000
          - metric: "5xxRate"
            operator: ">"
            threshold: 0.2
          - metric: "4xxRate"
            operator: ">"
            threshold: 0.3
      - name: b2
        addr: http://localhost:9090
        weight: 0
        metricThresholds:
          - metric: ResponseTime
            operator: ">"
            threshold: 1000
      - name: b3
        addr: http://localhost:9090
        weight: 0
        metricThresholds:
          - metric: ResponseTime
            operator: ">"
            threshold: 1000
  - name: Route3
    prefix: /route3/
    rewrite: /
    strategy:
      type: sticky
    backends:
      - name: b1
        addr: http://localhost:7070
        weight: 100
        metricThresholds:
          - metric: ResponseTime
            operator: ">"
            threshold: 1000
      - name: b2
        addr: http://localhost:9090
        weight: 0
        metricThresholds:
          - metric: ResponseTime
            operator: ">"
            threshold: 1000
      - name: b3
        addr: http://localhost:9090
        weight: 0
        metricThresholds:
          - metric: ResponseTime
            operator: ">"
            threshold: 1000
